name: quality-control
run-name: ${{ github.actor }} is running QA
on:
  push:
    branches-ignore: [ main,  auto-update-changelog ]

concurrency:
  group: qa-group
  cancel-in-progress: true

env:
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
  VERBOSITY_LEVEL: ${{ vars.VERBOSITY_LEVEL }}


jobs:
    build-n-test:
        runs-on: ubuntu-latest
        name: qa
        permissions: # This is required for the action configure-aws-credentials.
          id-token: write
        steps:
            - name: "fetch code"
              uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                check-latest: true
                cache-dependency-path: |
                  go.sum
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
                role-session-name: cicd-aws-session
                aws-region: ${{ vars.AWS_REGION }}
            - name: "Run test"
              uses: ./.github/actions/go-test
